import { StyleSheet, Platform } from 'react-native';

export const authStyles = StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: '#f0f4f8' },
    scrollContainer: { flexGrow: 1, justifyContent: 'center' },
    container: { width: '100%', padding: 20 },
    header: { alignItems: 'center', marginBottom: 32 },
    logo: { width: 100, height: 120, resizeMode: 'contain', alignSelf: 'center', marginTop: 10 },
    title: { fontSize: 28, fontWeight: 'bold', color: '#1a202c' },
    subtitle: { fontSize: 16, color: '#666' },
    card: {
        backgroundColor: 'white',
        borderRadius: 12,
        padding: 24,
        width: '100%',
        elevation: 4,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        marginBottom: 24,
    },
    cardTitle: { fontSize: 18, fontWeight: '600', marginBottom: 20, color: '#1a202c' },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 8,
        marginBottom: 16,
        backgroundColor: '#f9f9f9',
    },
    icon: { padding: 12 },
    input: { flex: 1, height: 50, paddingHorizontal: 10, fontSize: 16 },
    ktpButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: '#007AFF',
        borderStyle: 'dashed',
        borderRadius: 8,
        paddingVertical: 14,
        marginBottom: 20,
    },
    ktpButtonText: { color: '#007AFF', marginLeft: 10, fontWeight: '600', fontSize: 16 },
    primaryButton: { backgroundColor: '#007AFF', padding: 16, borderRadius: 8, alignItems: 'center' },
    primaryButtonText: { color: 'white', fontWeight: 'bold', fontSize: 16 },
    footerText: { textAlign: 'center', color: '#666', marginBottom: 20 },
});